### ISSUE TITLE
Query: Possible to input custom value instead of selecting?

### ISSUE THREAD

**Issue by shashj** [daqana/dqshiny#11]
Hi, is it possible to input a custom input into textbox based on suggestions instead of selecting an input from options?

Thank you for your help

**Comment by richardkunze** [comment]
Hi there. I'm not sure if I understand you correctly.

If you would like to allow unknown values in an autocomplete input you can set the `create` parameter to `TRUE`.

Otherwise, I would ask you to describe your issue more specifically.

**Comment by shashj** [comment]
Yeah I got that, the create parameter is not available in the package, is it deprecated?

**Comment by richardkunze** [comment]
It's currently only available in the github version, but I will release to CRAN very soon.

If you would like to try the github version beforehand, you can do so with `remotes::install_github("daqana/dqshiny")`

**Comment by shashj** [comment]
Great got it, I got that to work now
