### ISSUE TITLE
Problem with single quote in `options`

### ISSUE THREAD

**Issue by RemkoDuursma** [daqana/dqshiny#12]
I found that if the `options` in `autocomplete_input` contain single quotes ("Here 'tis", "Someone's problem"), the selection cannot be made (when clicking on the option, nothing happens).

An example:

```
library(shiny)
library(dqshiny)

opts <- c("Here 'tis", "Someone's problem", "OK text")


ui <- fluidPage(
  
  autocomplete_input("sel1", "Select", options = opts),
  
  tags$hr(),
  textOutput("txt_out")
  
  
)

server <- function(input, output, session) {
  
  output$txt_out <- renderText({
    
    input$sel1
    
  })
  
}

shinyApp(ui, server)
```

**Comment by richardkunze** [comment]
Hello, this issue seems to be related with #8 and should be fixed by now. Please make sure that you use the latest CRAN version `0.0.4`. You can do so with `packageVersion("dqshiny")`.

If you already use the latest version and the error persists, please tell me what OS/browser you are using.

**Comment by RemkoDuursma** [comment]
Yes, it was fixed, thanks.
