### ISSUE TITLE
Autocomplete returns name rather than value & length of name

### ISSUE THREAD

**Issue by zac-garland** [daqana/dqshiny#16]
Hi all,

Autocomplete looks really cool. But it doesn't work correctly with named inputs. 

As an example (reprex below), rather than returning `Apple Inc.` from `input$auto2` I'd want to return `AAPL` so I could pull stock prices from the ticker. 

Another thing I noticed is that long names are cutoff. Would it be hard to implement a `boolean` choice of whether the name was cutoff or the text was wrapped?

```
library(shiny)
library(dqshiny)
library(tidyverse)

opts <- read_csv("https://raw.githubusercontent.com/datasets/s-and-p-500-companies/master/data/constituents.csv")

opts <- setNames(opts$Symbol,opts$Name)

shinyApp(
  ui = fluidPage(
    fluidRow(
      column(3,
        autocomplete_input("auto2", "Named:", max_options = 1000,
          opts,create = T)
        # feel free to test this with select... and may get yourself a coffee
        # , selectInput("sel", "Select:", opts)
      ), column(3,
        tags$label("Value:"), verbatimTextOutput("val2", placeholder = TRUE)
      )
    )
  ),
  server = function(input, output) {
    output$val2 <- renderText(as.character(input$auto2))
  }
)
```

**Comment by richardkunze** [comment]
Hi there,

if you don't need to add unknown values, you can change the `create` parameter to its default value `false` and the selected value should be `AAPL` instead of `Apple Inc.`. But I'll fix this issue for value creation asap, thanks for pointing this out.

Regarding the other issue I can't reproduce any cut off behaviour. Could you show me an example?
![image](https://user-images.githubusercontent.com/43673581/89197585-3d6f0a80-d5ac-11ea-8f54-bd656479202c.png)

**Comment by zac-garland** [comment]
awesome, thanks @richardkunze 

Oddly enough, I wasn't able to replicate the cutoff name yesterday... which is odd given my experience a few days prior. Will let you know if it comes up again and I can create a reprex. 

One other thing that you may want to consider - turn autocomplete off, e.g. `<input autocomplete='off'></input>`. I accomplished this through javascript, but the reason is due to the autocomplete attribute (chrome as an example) will overlay the autocomplete_input dropdown, which becomes very annoying as you can't actually remove or minimize chrome's recommendation unless you do something like the below. Other than that, feel free to close if you fixed the create mode return value in dev. 

Thanks again!

```
  shinyjs::runjs('

    $(document).ready(function() {
        $("input").attr("autocomplete", "off");
    });

')

```

**Comment by richardkunze** [comment]
I disabled the browsers autocomplete functionality in the latest commit. Thank you for pointing this out!
