### ISSUE TITLE
Example reactive data with dq_render_handsontable()

### ISSUE THREAD

**Issue by mbacou** [daqana/dqshiny#6]
Could you kindly provide an example using a reactive data.frame? I'm trying to refactor code from `renderDT` to `dq_render_handsontable`, but I'm not able to pass the same reactive value. All I get is a non-descriptive error in RStudio: 

```
Listening on http://127.0.0.1:6031
Error :
```
Thx!

**Comment by mbacou** [comment]
Never mind, found the demo.

**Comment by stevepowell99** [comment]
I have the same issue, I can run the demo, but I can't see the code for it?

**Comment by richardkunze** [comment]
Here you can find the code of the [demo](https://github.com/daqana/dqshiny/tree/master/inst/shiny/base-features).

If this doesn't help, please provide a minimal working example of your problem and I will have a closer look at it.
