### ISSUE TITLE
Choosing option containing apostrophe

### ISSUE THREAD

**Issue by chrisvwn** [daqana/dqshiny#8]
There is an issue when one tries to select an option that contains an apostrophe. It updates the component with the portion of the string before the apostrophe.

Desired option highlighted
![Screenshot from 2020-01-20 16-37-13](https://user-images.githubusercontent.com/6387770/72730875-7234ea80-3ba3-11ea-8048-e512d0a5e6bb.png)

After selecting the option
![Screenshot from 2020-01-20 16-37-22](https://user-images.githubusercontent.com/6387770/72730890-7bbe5280-3ba3-11ea-82a5-c63c9b215d9b.png)

**Comment by richardkunze** [comment]
Hi, thank you for pointing this out. It should be fixed in the newest version.
Please check it out and tell me if there are any other issues.

**Comment by chrisvwn** [comment]
The fix works. Thank you!

I will let you know if I encounter any other issues.
